### ISSUE TITLE
arp updown mode skips notes

### ISSUE THREAD

**Issue by Windfisch** [twistedelectrons/TherapSID#12] opened 2023-02-13 23:25 UTC

**Comment by Sequence7** [comment] 2023-05-08 05:00
Yes noticed this today, to reproduce put on lowest range, if you play a 3 note chord, it will play all 3 notes on up, then miss the middle note on down and then forever after.

**Comment by Sequence7** [comment] 2023-06-21 00:50
Any chance of getting this one sorted @Windfisch @twisted-electrons, Filming the Arp section of the showcase video and up & down still being bugged is not ideal.

**Comment by twisted-electrons** [comment] 2023-06-21 07:14
@Sequence7 Hi Thanks for the note, I'll have a look at this ASAP

**Comment by twisted-electrons** [comment] 2023-07-03 19:35
@Sequence7 Hello - Should be fixed with the attached 2.4 beta firmware. I used the behaviour of the Back/Fourth monde of my Moog sub37 for inspiration - different from how I had originally intended... Instead of repeating up/down on each octave, it goes all the way up then all the way down the full range. More musical... enjoy!

**Comment by Sequence7** [comment] 2023-07-04 05:28
@twisted-electrons tested, is working great, I like the it arps on a single note, lets get some unique audiorate sounds too and some nasty drums, I think @thomasj said he might put a toggle in one day to make it not arp on one note, my c64 arps on one note, anyway thank you. shall continue my video;ing!

**Comment by twisted-electrons** [comment] 2023-07-04 07:18
@Sequence7 Cool thanks for your feedback, I went ahead and added the "NO ARP ON 1 KEY" switch to the tool.
Also I noticed that the note wouldn't update if you pressed a key with the arp on but set to a low rate.
Now the first key will update the pitch under those conditions.

You can try out the switch, already added to the tool, be sure to shift+refresh the page to see tool V1.1
https://twisted-electrons.com/tool/therapSID/

[TSID 2.4C.syx.zip](https://github.com/twistedelectrons/TherapSID/files/11945865/TSID.2.4C.syx.zip)

have fun!

**Comment by twisted-electrons** [comment] 2023-07-06 07:49
happiliy closing this issue folks...

**Closed by twisted-electrons** 2023-07-06 07:49 UTC
Labels: bug
