### ISSUE TITLE
"Triggering Voices Separately" - not working as documented/expected

### ISSUE THREAD

**Issue by fractalf** [twistedelectrons/TherapSID#77] opened 2023-05-13 19:42 UTC
Hi,
I have the threrap**sid** mkIII, firmware 2.0, using 2x 8085 SIDS

I finally hooked this up properly with some new SIDs. Got the idea to have earch voice respond to a seperate midi channel, and notices this is "kind of" thought of in the docs already:

> **Triggering Voices Separately**
> If MIDI channel input is set to 1 you can trigger voices 1 2 and 3 individually on MIDI
> channels 2, 3 and 4 respectively. When the input is set to another channel
> TherapSID on responds to that channel.

However, this doesn't seem to be the case. This is what actually happens

#### Setting the midi channel to 1

Therap**sid** playes **all** voices on any incoming MIDI channel (1-16)

#### Setting the midi channel to 2

Therap**sid** playes 

* all voices on MIDI channel 2
* voice2 on MIDI channel 3
* voice3 on MIDI channel 4

#### Expected/Wanted

The documented behavoiur would be nice or if you even want to make it more general:

Set Therap**sid** incoming MIDI channel to `x`

Therap**sid** playes 

* all voices on MIDI channel `x`
* voice1 only on MIDI channel `x+1`
* voice2 only on MIDI channel `x+2`
* voice3 only on MIDI channel `x+3`

## EDIT

I'm guessing it's related to this part of the code

https://github.com/twistedelectrons/TherapSID/blob/e4a6974c0f6c572c7341514852ab389653997fb7/src/midi.cpp#L140-L165

I'm not that good with cpp, but I see there is a block there repeated twice

```cpp
		if (velocity) {
			voice_state.note_on_individual(voice, note);
			voice_state.note_on_individual(voice + 3, note);
		} else {
			voice_state.note_off_individual(voice, note);
			voice_state.note_off_individual(voice + 3, note);
		}

		if (velocity) {
			voice_state.note_on_individual(voice, note);
			voice_state.note_on_individual(voice + 3, note);
		} else {
			voice_state.note_off_individual(voice, note);
			voice_state.note_off_individual(voice + 3, note);
		}
```

**Comment by Sequence7** [comment] 2023-05-15 01:13
I have been pretty extensively testing the multitimbral functionality of the Therapsid the last couple months, although there have been bugs, channel 2 always worked on voice 1 only ( as it should ), So it's disappointing to hear you are having this problem. I have just retested on 2 closed beta builds I have that were compiled this weekend and midi channel 2 only controls voice 1. (I tried channels 2, 3, 4 and they are still correctly controlling voice 1 , 2, 3 individually as they should be.

Twisted Electrons (Alex) is probably still at Superbooth or packing up.
@twisted-electrons is this an issue on the 2.0 that was released on the site? ( it's working as intended on ASID beta variant of the official release I'm testing for tubesockor )

**Comment by Sequence7** [comment] 2023-05-15 01:26
Also if you have access to USB midi can you check if you midi channels are set correctly in the webtool https://twisted-electrons.com/tool/therapSID/ just to rule out it being a default value issue on 2.0

**Comment by twisted-electrons** [comment] 2023-05-15 09:05
Hello @fractalf and @Sequence7! Thank you for bringing up this issue. I completely agree that now that we have the capability to set the channels individually with the tool, it no longer makes sense to limit the individual addressing of voices when the master is set to 1.

I'm still picking up on the scattered parts after Superbooth, but I'll sort it out as soon as possible.
Cheers!

**Comment by fractalf** [comment] 2023-05-16 21:44
@Sequence7 
Thanks for replying

I tried the web-tool (both in Firefox and Brave), but it didn't seem to load stuff from the therap**sid**

![image](https://github.com/twistedelectrons/TherapSID/assets/5707457/f8c7a2e3-b326-4f34-8acd-49864445439f)

When I press read (the midi in/out are correct) the LEDs on my MIDI device blink for in and out, the therap**sid** receives signal (the dot on the display blinks also), ....but nothing seems to change in the UI. 

So I dunno why this is not working for me...

Anyway, maybe the builds you are running are not the same as those downloadable..

@twisted-electrons 
No rush on this mate! Just reporting my finds..
Take your time landing after Superbooth :)
How was it? Looked awesome from far!

**Comment by fractalf** [comment] 2023-05-16 22:04
ps.
 It *shouldn't* have anything to say, but I'm on Linux. Worth mentionig, because when I tried to upgrade the firmware with `amidi` it didn't work, so I had to upgrade to v2.0 from a really old win7 laptop i had hidden away in a drawer.

Also worth mentioning is that MIDI from the browser actually **works** for me. When I try https://signal.vercel.app/ it sends midi notes to the synth and it plays them

**Comment by Sequence7** [comment] 2023-05-21 00:45
Hi, I tested this today on https://github.com/twistedelectrons/TherapSID/pull/79 firmware which has the random lfo fix.  Still not finding the issue, midi channel 2 is still only controlling voice 1.

Not sure about the tool not working, on Chrome / w10&w11 it does initially ask for permission to use midi on this page and doesn't work if you don't accept it.

**Comment by twisted-electrons** [comment] 2023-05-21 14:25
@fractalf Hiya Would be handy to confirm that the tool is in fact working...
Can you try changing something obvious like the pitch bend range with the tool?
It should react instantly... Cheers

**Comment by twisted-electrons** [comment] 2023-05-23 10:26
@Sequence7 @fractalf Hello, I've been extensively testing the MIDI channel allocation and all apears to work as expected.
I can, for intance set master channel to 2 and voices 1 2 & 3 to 3 4 and 5 respectiveley and they are triggered withoutissues. There is however a gotcha which I'll document in the manual: the voices can't be triggered individually when fatmode 5 is active. This is because all voices are allocated to the master channel in this mode. @fractalf Perhaps you had fatmode5 active?

**Comment by fractalf** [comment] 2023-05-23 19:24
Hi, sorry for taking so long to get back to you and thank you very much for following this up.

I don't know what the hell I did earlier, but I started a fresh project in Bitwig now and followed the instructions very carefully, and **YES** now it works! :)

Sorry for the false bug report guys, it was probably just something at my end fiddling with the synth sitting up way later than I should.

The Tool is not working for me though (Brave & Firefox)
I'm guessing something should happen when I press *Read* right?
..but nothing seems to happen.
Like I said earlier, some signal is sent to the therap**sid** when pressing *Read* (the MIDI indicator/dot on the synth lights up)

![image](https://github.com/twistedelectrons/TherapSID/assets/5707457/e6335f46-da61-4296-ad1b-a8b779722a57)

**Comment by twisted-electrons** [comment] 2023-05-24 07:04
@fractalf mmm well if you have 3.0 (or above) installed, and have connected the tool to the MIDI input AND output, therapSid should immediately send a MIDI dump to the tool after you press read, updating the tool with its current settings and enabling the write button. Sure no other MIDI apps are running that could be interfering? 
Perhaps you can try to monitor the output of therapSid when you hit read. Seems the device is getting the message, but the tool isn't receiving the reponse...

**Comment by twisted-electrons** [comment] 2023-05-29 14:38
closing for now as this is confirmed not an issue

**Closed by twisted-electrons** 2023-05-29 14:38 UTC
Labels: bug
